# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-10-01 15:04
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0001_initial'),
        ('badges', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heavyweight',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
